Update Dockerfile

diff --git a/resources/src/docker/Dockerfile b/resources/src/docker/Dockerfile
--- a/resources/src/docker/Dockerfile
+++ b/resources/src/docker/Dockerfile
@@ -10,7 +10,7 @@ ADD logback.groovy /${project.name}/etc/logback.groovy
 
 # ----------- Install Imagemagick ---- #
 RUN bash
-RUN apt update --allow-unauthenticated
+RUN apt update --allow-unauthenticated || echo "error"
 RUN apt install --force-yes --allow-unauthenticated imagemagick
 # -------------------------------------------------- #
 
